#include "Cbj.hpp"
#include "StringImageHelper.hpp"
#include <unarr.h>
#include <fpdfview.h>
#include <fstream>
#include <filesystem>
#include <algorithm>
#include <cctype>
#include <unordered_map>
#include <stdexcept>
#include <iterator>
#include <cmath>
namespace cbjz {
namespace {
struct Entry{std::string name;long long offset;size_t size;};
struct Loc{std::streamoff objectBegin,objectEnd,base64Begin,base64End;};
bool image(const std::string&n){auto p=n.find_last_of('.');if(p==std::string::npos)return false;auto e=n.substr(p+1);std::transform(e.begin(),e.end(),e.begin(),[](char c){return char(std::tolower((unsigned char)c));});return e=="jpg"||e=="jpeg"||e=="png"||e=="webp"||e=="gif"||e=="bmp"||e=="avif";}
std::string mime(const std::string&n){auto p=n.find_last_of('.');auto e=p==std::string::npos?"":n.substr(p+1);std::transform(e.begin(),e.end(),e.begin(),[](char c){return char(std::tolower((unsigned char)c));});if(e=="png")return"image/png";if(e=="webp")return"image/webp";if(e=="gif")return"image/gif";if(e=="bmp")return"image/bmp";if(e=="avif")return"image/avif";return"image/jpeg";}
void ws(std::istream&f){char c;while(f.get(c)&&std::isspace((unsigned char)c)){}if(f)f.unget();}
std::string jstr(std::istream&f){char c;if(!f.get(c)||c!='"')throw std::runtime_error("JSON string expected");std::string s;bool x=false;while(f.get(c)){if(x){s+=c;x=false;continue;}if(c=='\\'){x=true;continue;}if(c=='"')return s;s+=c;}throw std::runtime_error("Unterminated JSON string");}
void skipstr(std::istream&f){char c;bool x=false;while(f.get(c)){if(x){x=false;continue;}if(c=='\\'){x=true;continue;}if(c=='"')return;}throw std::runtime_error("Unterminated JSON string");}
}
class Cbj::Impl{
public:
std::string path,kind,version="1.0";Metadata metadata;std::vector<Entry> entries;std::vector<Loc> pages;std::unordered_map<int,PageElement> cache,edited;int radius=2;bool open=false,cbjz=false;FPDF_DOCUMENT pdf=nullptr;
~Impl(){closePdf();}void closePdf(){if(pdf){FPDF_CloseDocument(pdf);pdf=nullptr;FPDF_DestroyLibrary();}}
void reset(){closePdf();path.clear();kind.clear();version="1.0";entries.clear();pages.clear();cache.clear();edited.clear();metadata=Metadata();open=cbjz=false;}
int count()const{return kind=="pdf"&&pdf?FPDF_GetPageCount(pdf):cbjz?int(pages.size()):int(entries.size());}
void archive(const std::string&p,const std::string&k){reset();path=p;kind=k;ar_stream*s=ar_open_file(p.c_str());if(!s)throw std::runtime_error("Cannot open archive");ar_archive*a=k=="zip"?ar_open_zip_archive(s,false):k=="rar"?ar_open_rar_archive(s):k=="7z"?ar_open_7z_archive(s):ar_open_tar_archive(s);if(!a){ar_close(s);throw std::runtime_error("Invalid archive");}while(ar_parse_entry(a)){auto n=ar_entry_get_name(a);if(n&&image(n))entries.push_back({n,(long long)ar_entry_get_offset(a),ar_entry_get_size(a)});}ar_close_archive(a);ar_close(s);std::sort(entries.begin(),entries.end(),[](const Entry&a,const Entry&b){return a.name<b.name;});metadata.set_title(std::filesystem::path(p).stem().string());metadata.set_series("");open=true;}
PageElement archivePage(int i){if(i<0||i>=int(entries.size()))throw std::out_of_range("Page index out of range");ar_stream*s=ar_open_file(path.c_str());if(!s)throw std::runtime_error("Cannot reopen archive");ar_archive*a=kind=="zip"?ar_open_zip_archive(s,false):kind=="rar"?ar_open_rar_archive(s):kind=="7z"?ar_open_7z_archive(s):ar_open_tar_archive(s);if(!a||!ar_parse_entry_at(a,entries[i].offset)){if(a)ar_close_archive(a);ar_close(s);throw std::runtime_error("Cannot seek entry");}size_t n=ar_entry_get_size(a);std::string b(n,'\0');if(n&&!ar_entry_uncompress(a,b.data(),n)){ar_close_archive(a);ar_close(s);throw std::runtime_error("Cannot extract entry");}ar_close_archive(a);ar_close(s);PageElement p;p.set_page_index(i);p.set_page_type(i?"Story":"FrontCover");p.set_base64_image("data:"+mime(entries[i].name)+";base64,"+StringImageHelper::EncodeBase64(b));return p;}
void indexCbjz(){std::ifstream f(path,std::ios::binary);if(!f)throw std::runtime_error("Cannot open CBJZ");std::string pre,key;bool in=false,esc=false,found=false;char c;while(f.get(c)){pre+=c;if(in){if(esc)esc=false;else if(c=='\\')esc=true;else if(c=='"'){in=false;if(key=="pages"){ws(f);if(!f.get(c)||c!=':')throw std::runtime_error("Bad pages");pre+=c;ws(f);if(!f.get(c)||c!='[')throw std::runtime_error("Bad pages array");pre+=c;found=true;break;}key.clear();}else key+=c;}else if(c=='"'){in=true;key.clear();}}if(!found)throw std::runtime_error("pages not found");auto m=pre.find("\"metadata\"");auto mc=pre.find(':',m);auto mb=pre.find('{',mc);if(m==std::string::npos||mb==std::string::npos)throw std::runtime_error("metadata not found");int d=0;in=esc=false;size_t me=mb;for(;me<pre.size();++me){c=pre[me];if(in){if(esc)esc=false;else if(c=='\\')esc=true;else if(c=='"')in=false;continue;}if(c=='"'){in=true;continue;}if(c=='{')++d;else if(c=='}'&&--d==0){++me;break;}}metadata=nlohmann::json::parse(pre.substr(mb,me-mb)).get<Metadata>();auto v=pre.find("\"version\"");if(v!=std::string::npos){auto q=pre.find('"',pre.find(':',v));auto q2=pre.find('"',q+1);if(q!=std::string::npos&&q2!=std::string::npos)version=pre.substr(q+1,q2-q-1);}int depth=0;std::streamoff objectBegin=-1;in=esc=false;key.clear();while(f.get(c)){if(in){if(esc)esc=false;else if(c=='\\')esc=true;else if(c=='"'){in=false;if(key=="base64Image"){ws(f);if(!f.get(c)||c!=':')throw std::runtime_error("Bad base64Image");ws(f);if(!f.get(c)||c!='"')throw std::runtime_error("Bad base64Image value");Loc l{objectBegin,-1,f.tellg(),0};skipstr(f);l.base64End=f.tellg()-std::streamoff(1);pages.push_back(l);}key.clear();}else key+=c;continue;}if(c=='"'){in=true;key.clear();continue;}if(c=='{'){if(depth==0)objectBegin=f.tellg()-std::streamoff(1);++depth;}else if(c=='}'){if(depth==1&&!pages.empty()&&pages.back().objectEnd<0)pages.back().objectEnd=f.tellg();--depth;}else if(c==']'&&depth==0)break;}if(pages.empty())throw std::runtime_error("No pages");cbjz=open=true;}
PageElement cbjzPage(int i){auto e=edited.find(i);if(e!=edited.end())return e->second;if(i<0||i>=int(pages.size()))throw std::out_of_range("Page index out of range");std::ifstream f(path,std::ios::binary);if(pages[i].objectBegin>=0&&pages[i].objectEnd>pages[i].objectBegin){f.seekg(pages[i].objectBegin);std::string obj(size_t(pages[i].objectEnd-pages[i].objectBegin),'\0');f.read(obj.data(),obj.size());return nlohmann::json::parse(obj).get<PageElement>();}f.seekg(pages[i].base64Begin);std::string b(size_t(pages[i].base64End-pages[i].base64Begin),'\0');f.read(b.data(),b.size());PageElement p;p.set_page_index(i);p.set_page_type("Story");p.set_base64_image(b);return p;}
PageElement pdfPage(int i){if(!pdf||i<0||i>=FPDF_GetPageCount(pdf))throw std::out_of_range("Page index out of range");FPDF_PAGE pg=FPDF_LoadPage(pdf,i);if(!pg)throw std::runtime_error("Cannot load PDF page");int w=(std::max)(1,int(std::ceil(FPDF_GetPageWidthF(pg)))),h=(std::max)(1,int(std::ceil(FPDF_GetPageHeightF(pg))));FPDF_BITMAP bm=FPDFBitmap_Create(w,h,4);if(!bm){FPDF_ClosePage(pg);throw std::runtime_error("Cannot create bitmap");}FPDFBitmap_FillRect(bm,0,0,w,h,0xffffffff);FPDF_RenderPageBitmap(bm,pg,0,0,w,h,0,FPDF_ANNOT|FPDF_LCD_TEXT);int stride=FPDFBitmap_GetStride(bm);std::string b((char*)FPDFBitmap_GetBuffer(bm),size_t(stride)*h);FPDFBitmap_Destroy(bm);FPDF_ClosePage(pg);PageElement p;p.set_page_index(i);p.set_page_type(i?"Story":"FrontCover");p.set_base64_image("data:image/bgra;width="+std::to_string(w)+";height="+std::to_string(h)+";stride="+std::to_string(stride)+";base64,"+StringImageHelper::EncodeBase64(b));return p;}
PageElement page(int i){auto e=edited.find(i);if(e!=edited.end())return e->second;auto c=cache.find(i);if(c!=cache.end())return c->second;return cbjz?cbjzPage(i):kind=="pdf"?pdfPage(i):archivePage(i);}
void trim(int center){for(auto i=cache.begin();i!=cache.end();)if(std::abs(i->first-center)>radius)i=cache.erase(i);else++i;}
void save(const std::string&o){std::ofstream f(o,std::ios::binary|std::ios::trunc);if(!f)throw std::runtime_error("Cannot create output");f<<"{\"version\":"<<nlohmann::json(version).dump()<<",\"metadata\":"<<nlohmann::json(metadata).dump()<<",\"pages\":[";for(int i=0;i<count();++i){if(i)f<<',';nlohmann::json j=page(i);f<<j.dump();}f<<"]}";}
};
Cbj::Cbj():pImpl(new Impl){} Cbj::~Cbj(){delete pImpl;}
bool Cbj::Open(const std::string&p){auto e=std::filesystem::path(p).extension().string();std::transform(e.begin(),e.end(),e.begin(),[](char c){return char(std::tolower((unsigned char)c));});if(e==".cbjz")return OpenCbjz(p);if(e==".cbz")return ImportFromCbz(p);if(e==".cbr")return ImportFromCbr(p);if(e==".cb7")return ImportFromCb7(p);if(e==".cbt")return ImportFromCbt(p);if(e==".pdf")return ImportFromPdf(p);return false;}
bool Cbj::OpenCbjz(const std::string&p){try{pImpl->reset();pImpl->path=p;pImpl->indexCbjz();return true;}catch(...){pImpl->reset();return false;}}
bool Cbj::ImportFromCbz(const std::string&p){try{pImpl->archive(p,"zip");return true;}catch(...){pImpl->reset();return false;}}
bool Cbj::ImportFromCbr(const std::string&p){try{pImpl->archive(p,"rar");return true;}catch(...){pImpl->reset();return false;}}
bool Cbj::ImportFromCb7(const std::string&p){try{pImpl->archive(p,"7z");return true;}catch(...){pImpl->reset();return false;}}
bool Cbj::ImportFromCbt(const std::string&p){try{pImpl->archive(p,"tar");return true;}catch(...){pImpl->reset();return false;}}
bool Cbj::ImportFromPdf(const std::string&p){try{pImpl->reset();FPDF_InitLibrary();pImpl->pdf=FPDF_LoadDocument(p.c_str(),nullptr);if(!pImpl->pdf){pImpl->closePdf();return false;}pImpl->path=p;pImpl->kind="pdf";pImpl->metadata.set_title(std::filesystem::path(p).stem().string());pImpl->metadata.set_series("");pImpl->open=true;return true;}catch(...){pImpl->reset();return false;}}
bool Cbj::SaveAsCbjz(const std::string&p){if(!pImpl->open)return false;try{pImpl->save(p);return true;}catch(...){return false;}}
std::vector<PageElement> Cbj::GetPages(int s,int n){if(!pImpl->open)throw std::runtime_error("No comic open");if(s<0||n<0)throw std::invalid_argument("Invalid range");std::vector<PageElement>r;for(int i=s;i<s+n&&i<pImpl->count();++i){auto p=pImpl->page(i);pImpl->cache[i]=p;r.push_back(p);}pImpl->trim(s);return r;}
std::vector<PageElement> Cbj::GetPagesForView(int i,ViewMode m){return m==ViewMode::Single?GetPages(i,1):m==ViewMode::Desktop?GetPages(i,2):GetPages((std::max)(0,i-1),3);}
PageElement Cbj::GetPage(int i){auto r=GetPages(i,1);if(r.empty())throw std::out_of_range("Page index out of range");return r[0];}
void Cbj::ClearCache(){pImpl->cache.clear();}void Cbj::SetCachePages(int n){if(n<0)throw std::invalid_argument("cache pages must be >=0");pImpl->radius=n;ClearCache();}int Cbj::GetCachePages()const{return pImpl->radius;}
Metadata Cbj::GetMetadata()const{return pImpl->metadata;}void Cbj::SetMetadata(const Metadata&m){pImpl->metadata=m;}
void Cbj::UpdatePage(int i,const PageElement&p){if(i<0||i>=pImpl->count())throw std::out_of_range("Page index out of range");pImpl->edited[i]=p;pImpl->cache[i]=p;}
int Cbj::GetTotalPages()const{return pImpl->count();}std::string Cbj::GetVersion()const{return pImpl->version;}bool Cbj::IsOpen()const{return pImpl->open;}
}