//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace ComicBookJson.Cbj {

public class CreatorElement : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal CreatorElement(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(CreatorElement obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(CreatorElement obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~CreatorElement() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          cbjPINVOKE.delete_CreatorElement(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public CreatorElement() : this(cbjPINVOKE.new_CreatorElement(), true) {
  }

  public string get_name() {
    string ret = cbjPINVOKE.CreatorElement_get_name(swigCPtr);
    return ret;
  }

  public SWIGTYPE_p_std__string get_mutable_name() {
    SWIGTYPE_p_std__string ret = new SWIGTYPE_p_std__string(cbjPINVOKE.CreatorElement_get_mutable_name(swigCPtr), false);
    return ret;
  }

  public void set_name(string value) {
    cbjPINVOKE.CreatorElement_set_name(swigCPtr, value);
    if (cbjPINVOKE.SWIGPendingException.Pending) throw cbjPINVOKE.SWIGPendingException.Retrieve();
  }

  public string get_role() {
    string ret = cbjPINVOKE.CreatorElement_get_role(swigCPtr);
    return ret;
  }

  public SWIGTYPE_p_std__string get_mutable_role() {
    SWIGTYPE_p_std__string ret = new SWIGTYPE_p_std__string(cbjPINVOKE.CreatorElement_get_mutable_role(swigCPtr), false);
    return ret;
  }

  public void set_role(string value) {
    cbjPINVOKE.CreatorElement_set_role(swigCPtr, value);
    if (cbjPINVOKE.SWIGPendingException.Pending) throw cbjPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
