//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace ComicBookJson.Cbj {

public class PageTagElement : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal PageTagElement(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(PageTagElement obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(PageTagElement obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~PageTagElement() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          cbjPINVOKE.delete_PageTagElement(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public PageTagElement() : this(cbjPINVOKE.new_PageTagElement(), true) {
  }

  public string get_tag_id() {
    string ret = cbjPINVOKE.PageTagElement_get_tag_id(swigCPtr);
    return ret;
  }

  public SWIGTYPE_p_std__string get_mutable_tag_id() {
    SWIGTYPE_p_std__string ret = new SWIGTYPE_p_std__string(cbjPINVOKE.PageTagElement_get_mutable_tag_id(swigCPtr), false);
    return ret;
  }

  public void set_tag_id(string value) {
    cbjPINVOKE.PageTagElement_set_tag_id(swigCPtr, value);
    if (cbjPINVOKE.SWIGPendingException.Pending) throw cbjPINVOKE.SWIGPendingException.Retrieve();
  }

  public double get_x() {
    double ret = cbjPINVOKE.PageTagElement_get_x(swigCPtr);
    return ret;
  }

  public SWIGTYPE_p_double get_mutable_x() {
    SWIGTYPE_p_double ret = new SWIGTYPE_p_double(cbjPINVOKE.PageTagElement_get_mutable_x(swigCPtr), false);
    return ret;
  }

  public void set_x(double value) {
    cbjPINVOKE.PageTagElement_set_x(swigCPtr, value);
  }

  public double get_y() {
    double ret = cbjPINVOKE.PageTagElement_get_y(swigCPtr);
    return ret;
  }

  public SWIGTYPE_p_double get_mutable_y() {
    SWIGTYPE_p_double ret = new SWIGTYPE_p_double(cbjPINVOKE.PageTagElement_get_mutable_y(swigCPtr), false);
    return ret;
  }

  public void set_y(double value) {
    cbjPINVOKE.PageTagElement_set_y(swigCPtr, value);
  }

}

}
