//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace ComicBookJson.Cbj {

public class PageElement : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal PageElement(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(PageElement obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(PageElement obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~PageElement() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          cbjPINVOKE.delete_PageElement(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public PageElement() : this(cbjPINVOKE.new_PageElement(), true) {
  }

  public string get_base64_image() {
    string ret = cbjPINVOKE.PageElement_get_base64_image(swigCPtr);
    return ret;
  }

  public SWIGTYPE_p_std__string get_mutable_base64_image() {
    SWIGTYPE_p_std__string ret = new SWIGTYPE_p_std__string(cbjPINVOKE.PageElement_get_mutable_base64_image(swigCPtr), false);
    return ret;
  }

  public void set_base64_image(string value) {
    cbjPINVOKE.PageElement_set_base64_image(swigCPtr, value);
    if (cbjPINVOKE.SWIGPendingException.Pending) throw cbjPINVOKE.SWIGPendingException.Retrieve();
  }

  public SWIGTYPE_p_int64_t get_page_index() {
    SWIGTYPE_p_int64_t ret = new SWIGTYPE_p_int64_t(cbjPINVOKE.PageElement_get_page_index(swigCPtr), false);
    return ret;
  }

  public SWIGTYPE_p_int64_t get_mutable_page_index() {
    SWIGTYPE_p_int64_t ret = new SWIGTYPE_p_int64_t(cbjPINVOKE.PageElement_get_mutable_page_index(swigCPtr), false);
    return ret;
  }

  public void set_page_index(SWIGTYPE_p_int64_t value) {
    cbjPINVOKE.PageElement_set_page_index(swigCPtr, SWIGTYPE_p_int64_t.getCPtr(value));
    if (cbjPINVOKE.SWIGPendingException.Pending) throw cbjPINVOKE.SWIGPendingException.Retrieve();
  }

  public SWIGTYPE_p_std__optionalT_std__vectorT_cbjz__PageTagElement_t_t get_page_tags() {
    SWIGTYPE_p_std__optionalT_std__vectorT_cbjz__PageTagElement_t_t ret = new SWIGTYPE_p_std__optionalT_std__vectorT_cbjz__PageTagElement_t_t(cbjPINVOKE.PageElement_get_page_tags(swigCPtr), false);
    return ret;
  }

  public SWIGTYPE_p_std__optionalT_std__vectorT_cbjz__PageTagElement_t_t get_mutable_page_tags() {
    SWIGTYPE_p_std__optionalT_std__vectorT_cbjz__PageTagElement_t_t ret = new SWIGTYPE_p_std__optionalT_std__vectorT_cbjz__PageTagElement_t_t(cbjPINVOKE.PageElement_get_mutable_page_tags(swigCPtr), false);
    return ret;
  }

  public void set_page_tags(SWIGTYPE_p_std__optionalT_std__vectorT_cbjz__PageTagElement_t_t value) {
    cbjPINVOKE.PageElement_set_page_tags(swigCPtr, SWIGTYPE_p_std__optionalT_std__vectorT_cbjz__PageTagElement_t_t.getCPtr(value));
    if (cbjPINVOKE.SWIGPendingException.Pending) throw cbjPINVOKE.SWIGPendingException.Retrieve();
  }

  public SWIGTYPE_p_std__optionalT_std__string_t get_page_type() {
    SWIGTYPE_p_std__optionalT_std__string_t ret = new SWIGTYPE_p_std__optionalT_std__string_t(cbjPINVOKE.PageElement_get_page_type(swigCPtr), false);
    return ret;
  }

  public SWIGTYPE_p_std__optionalT_std__string_t get_mutable_page_type() {
    SWIGTYPE_p_std__optionalT_std__string_t ret = new SWIGTYPE_p_std__optionalT_std__string_t(cbjPINVOKE.PageElement_get_mutable_page_type(swigCPtr), false);
    return ret;
  }

  public void set_page_type(SWIGTYPE_p_std__optionalT_std__string_t value) {
    cbjPINVOKE.PageElement_set_page_type(swigCPtr, SWIGTYPE_p_std__optionalT_std__string_t.getCPtr(value));
    if (cbjPINVOKE.SWIGPendingException.Pending) throw cbjPINVOKE.SWIGPendingException.Retrieve();
  }

  public SWIGTYPE_p_std__optionalT_std__string_t get_summary() {
    SWIGTYPE_p_std__optionalT_std__string_t ret = new SWIGTYPE_p_std__optionalT_std__string_t(cbjPINVOKE.PageElement_get_summary(swigCPtr), true);
    return ret;
  }

  public void set_summary(SWIGTYPE_p_std__optionalT_std__string_t value) {
    cbjPINVOKE.PageElement_set_summary(swigCPtr, SWIGTYPE_p_std__optionalT_std__string_t.getCPtr(value));
    if (cbjPINVOKE.SWIGPendingException.Pending) throw cbjPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
