//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.5.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace ComicBookJson.Cbj {

public class CbjBuilder : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal CbjBuilder(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(CbjBuilder obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(CbjBuilder obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~CbjBuilder() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          cbjPINVOKE.delete_CbjBuilder(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public CbjBuilder() : this(cbjPINVOKE.new_CbjBuilder(), true) {
  }

  public CbjBuilder SetVersion(string arg0) {
    CbjBuilder ret = new CbjBuilder(cbjPINVOKE.CbjBuilder_SetVersion(swigCPtr, arg0), false);
    if (cbjPINVOKE.SWIGPendingException.Pending) throw cbjPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public CbjBuilder SetMetadata(string title, string series) {
    CbjBuilder ret = new CbjBuilder(cbjPINVOKE.CbjBuilder_SetMetadata(swigCPtr, title, series), false);
    if (cbjPINVOKE.SWIGPendingException.Pending) throw cbjPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public CbjBuilder SetIssue(string arg0) {
    CbjBuilder ret = new CbjBuilder(cbjPINVOKE.CbjBuilder_SetIssue(swigCPtr, arg0), false);
    if (cbjPINVOKE.SWIGPendingException.Pending) throw cbjPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public CbjBuilder SetVolume(SWIGTYPE_p_std__int64_t arg0) {
    CbjBuilder ret = new CbjBuilder(cbjPINVOKE.CbjBuilder_SetVolume(swigCPtr, SWIGTYPE_p_std__int64_t.getCPtr(arg0)), false);
    if (cbjPINVOKE.SWIGPendingException.Pending) throw cbjPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public CbjBuilder SetPublisher(string arg0) {
    CbjBuilder ret = new CbjBuilder(cbjPINVOKE.CbjBuilder_SetPublisher(swigCPtr, arg0), false);
    if (cbjPINVOKE.SWIGPendingException.Pending) throw cbjPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public CbjBuilder SetLanguage(string arg0) {
    CbjBuilder ret = new CbjBuilder(cbjPINVOKE.CbjBuilder_SetLanguage(swigCPtr, arg0), false);
    if (cbjPINVOKE.SWIGPendingException.Pending) throw cbjPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public CbjBuilder SetSummary(string arg0) {
    CbjBuilder ret = new CbjBuilder(cbjPINVOKE.CbjBuilder_SetSummary(swigCPtr, arg0), false);
    if (cbjPINVOKE.SWIGPendingException.Pending) throw cbjPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public CbjBuilder AddGenre(string arg0) {
    CbjBuilder ret = new CbjBuilder(cbjPINVOKE.CbjBuilder_AddGenre(swigCPtr, arg0), false);
    if (cbjPINVOKE.SWIGPendingException.Pending) throw cbjPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public CbjBuilder AddCreator(string arg0, string arg1) {
    CbjBuilder ret = new CbjBuilder(cbjPINVOKE.CbjBuilder_AddCreator(swigCPtr, arg0, arg1), false);
    if (cbjPINVOKE.SWIGPendingException.Pending) throw cbjPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public CbjBuilder AddTag(string arg0, string arg1, Type arg2) {
    CbjBuilder ret = new CbjBuilder(cbjPINVOKE.CbjBuilder_AddTag(swigCPtr, arg0, arg1, (int)arg2), false);
    if (cbjPINVOKE.SWIGPendingException.Pending) throw cbjPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public CbjBuilder AddChapter(string arg0, SWIGTYPE_p_std__int64_t arg1, string summary) {
    CbjBuilder ret = new CbjBuilder(cbjPINVOKE.CbjBuilder_AddChapter__SWIG_0(swigCPtr, arg0, SWIGTYPE_p_std__int64_t.getCPtr(arg1), summary), false);
    if (cbjPINVOKE.SWIGPendingException.Pending) throw cbjPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public CbjBuilder AddChapter(string arg0, SWIGTYPE_p_std__int64_t arg1) {
    CbjBuilder ret = new CbjBuilder(cbjPINVOKE.CbjBuilder_AddChapter__SWIG_1(swigCPtr, arg0, SWIGTYPE_p_std__int64_t.getCPtr(arg1)), false);
    if (cbjPINVOKE.SWIGPendingException.Pending) throw cbjPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public CbjBuilder AddPageBase64(string arg0, string pageType, string summary) {
    CbjBuilder ret = new CbjBuilder(cbjPINVOKE.CbjBuilder_AddPageBase64__SWIG_0(swigCPtr, arg0, pageType, summary), false);
    if (cbjPINVOKE.SWIGPendingException.Pending) throw cbjPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public CbjBuilder AddPageBase64(string arg0, string pageType) {
    CbjBuilder ret = new CbjBuilder(cbjPINVOKE.CbjBuilder_AddPageBase64__SWIG_1(swigCPtr, arg0, pageType), false);
    if (cbjPINVOKE.SWIGPendingException.Pending) throw cbjPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public CbjBuilder AddPageBase64(string arg0) {
    CbjBuilder ret = new CbjBuilder(cbjPINVOKE.CbjBuilder_AddPageBase64__SWIG_2(swigCPtr, arg0), false);
    if (cbjPINVOKE.SWIGPendingException.Pending) throw cbjPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public CbjBuilder AddPageBytes(string arg0, string pageType, string summary) {
    CbjBuilder ret = new CbjBuilder(cbjPINVOKE.CbjBuilder_AddPageBytes__SWIG_0(swigCPtr, arg0, pageType, summary), false);
    if (cbjPINVOKE.SWIGPendingException.Pending) throw cbjPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public CbjBuilder AddPageBytes(string arg0, string pageType) {
    CbjBuilder ret = new CbjBuilder(cbjPINVOKE.CbjBuilder_AddPageBytes__SWIG_1(swigCPtr, arg0, pageType), false);
    if (cbjPINVOKE.SWIGPendingException.Pending) throw cbjPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public CbjBuilder AddPageBytes(string arg0) {
    CbjBuilder ret = new CbjBuilder(cbjPINVOKE.CbjBuilder_AddPageBytes__SWIG_2(swigCPtr, arg0), false);
    if (cbjPINVOKE.SWIGPendingException.Pending) throw cbjPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public CbjzV1Schema Build() {
    CbjzV1Schema ret = new CbjzV1Schema(cbjPINVOKE.CbjBuilder_Build(swigCPtr), true);
    return ret;
  }

  public bool Save(string arg0) {
    bool ret = cbjPINVOKE.CbjBuilder_Save(swigCPtr, arg0);
    if (cbjPINVOKE.SWIGPendingException.Pending) throw cbjPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
