//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.5.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace ComicBookJson.Cbj {

class cbjPINVOKE {

  protected class SWIGExceptionHelper {

    public delegate void ExceptionDelegate(string message);
    public delegate void ExceptionArgumentDelegate(string message, string paramName);

    static ExceptionDelegate applicationDelegate = new ExceptionDelegate(SetPendingApplicationException);
    static ExceptionDelegate arithmeticDelegate = new ExceptionDelegate(SetPendingArithmeticException);
    static ExceptionDelegate divideByZeroDelegate = new ExceptionDelegate(SetPendingDivideByZeroException);
    static ExceptionDelegate indexOutOfRangeDelegate = new ExceptionDelegate(SetPendingIndexOutOfRangeException);
    static ExceptionDelegate invalidCastDelegate = new ExceptionDelegate(SetPendingInvalidCastException);
    static ExceptionDelegate invalidOperationDelegate = new ExceptionDelegate(SetPendingInvalidOperationException);
    static ExceptionDelegate ioDelegate = new ExceptionDelegate(SetPendingIOException);
    static ExceptionDelegate nullReferenceDelegate = new ExceptionDelegate(SetPendingNullReferenceException);
    static ExceptionDelegate outOfMemoryDelegate = new ExceptionDelegate(SetPendingOutOfMemoryException);
    static ExceptionDelegate overflowDelegate = new ExceptionDelegate(SetPendingOverflowException);
    static ExceptionDelegate systemDelegate = new ExceptionDelegate(SetPendingSystemException);

    static ExceptionArgumentDelegate argumentDelegate = new ExceptionArgumentDelegate(SetPendingArgumentException);
    static ExceptionArgumentDelegate argumentNullDelegate = new ExceptionArgumentDelegate(SetPendingArgumentNullException);
    static ExceptionArgumentDelegate argumentOutOfRangeDelegate = new ExceptionArgumentDelegate(SetPendingArgumentOutOfRangeException);

    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="SWIGRegisterExceptionCallbacks_cbj")]
    public static extern void SWIGRegisterExceptionCallbacks_cbj(
                                ExceptionDelegate applicationDelegate,
                                ExceptionDelegate arithmeticDelegate,
                                ExceptionDelegate divideByZeroDelegate, 
                                ExceptionDelegate indexOutOfRangeDelegate, 
                                ExceptionDelegate invalidCastDelegate,
                                ExceptionDelegate invalidOperationDelegate,
                                ExceptionDelegate ioDelegate,
                                ExceptionDelegate nullReferenceDelegate,
                                ExceptionDelegate outOfMemoryDelegate, 
                                ExceptionDelegate overflowDelegate, 
                                ExceptionDelegate systemExceptionDelegate);

    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="SWIGRegisterExceptionArgumentCallbacks_cbj")]
    public static extern void SWIGRegisterExceptionCallbacksArgument_cbj(
                                ExceptionArgumentDelegate argumentDelegate,
                                ExceptionArgumentDelegate argumentNullDelegate,
                                ExceptionArgumentDelegate argumentOutOfRangeDelegate);

    static void SetPendingApplicationException(string message) {
      SWIGPendingException.Set(new global::System.ApplicationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArithmeticException(string message) {
      SWIGPendingException.Set(new global::System.ArithmeticException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingDivideByZeroException(string message) {
      SWIGPendingException.Set(new global::System.DivideByZeroException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIndexOutOfRangeException(string message) {
      SWIGPendingException.Set(new global::System.IndexOutOfRangeException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidCastException(string message) {
      SWIGPendingException.Set(new global::System.InvalidCastException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidOperationException(string message) {
      SWIGPendingException.Set(new global::System.InvalidOperationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIOException(string message) {
      SWIGPendingException.Set(new global::System.IO.IOException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingNullReferenceException(string message) {
      SWIGPendingException.Set(new global::System.NullReferenceException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOutOfMemoryException(string message) {
      SWIGPendingException.Set(new global::System.OutOfMemoryException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOverflowException(string message) {
      SWIGPendingException.Set(new global::System.OverflowException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingSystemException(string message) {
      SWIGPendingException.Set(new global::System.SystemException(message, SWIGPendingException.Retrieve()));
    }

    static void SetPendingArgumentException(string message, string paramName) {
      SWIGPendingException.Set(new global::System.ArgumentException(message, paramName, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArgumentNullException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentNullException(paramName, message));
    }
    static void SetPendingArgumentOutOfRangeException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentOutOfRangeException(paramName, message));
    }

    static SWIGExceptionHelper() {
      SWIGRegisterExceptionCallbacks_cbj(
                                applicationDelegate,
                                arithmeticDelegate,
                                divideByZeroDelegate,
                                indexOutOfRangeDelegate,
                                invalidCastDelegate,
                                invalidOperationDelegate,
                                ioDelegate,
                                nullReferenceDelegate,
                                outOfMemoryDelegate,
                                overflowDelegate,
                                systemDelegate);

      SWIGRegisterExceptionCallbacksArgument_cbj(
                                argumentDelegate,
                                argumentNullDelegate,
                                argumentOutOfRangeDelegate);
    }
  }

  protected static SWIGExceptionHelper swigExceptionHelper = new SWIGExceptionHelper();

  public class SWIGPendingException {
    [global::System.ThreadStatic]
    private static global::System.Exception pendingException = null;
    private static int numExceptionsPending = 0;
    private static global::System.Object exceptionsLock = null;

    public static bool Pending {
      get {
        bool pending = false;
        if (numExceptionsPending > 0)
          if (pendingException != null)
            pending = true;
        return pending;
      } 
    }

    public static void Set(global::System.Exception e) {
      if (pendingException != null)
        throw new global::System.ApplicationException("FATAL: An earlier pending exception from unmanaged code was missed and thus not thrown (" + pendingException.ToString() + ")", e);
      pendingException = e;
      lock(exceptionsLock) {
        numExceptionsPending++;
      }
    }

    public static global::System.Exception Retrieve() {
      global::System.Exception e = null;
      if (numExceptionsPending > 0) {
        if (pendingException != null) {
          e = pendingException;
          pendingException = null;
          lock(exceptionsLock) {
            numExceptionsPending--;
          }
        }
      }
      return e;
    }

    static SWIGPendingException() {
      exceptionsLock = new global::System.Object();
    }
  }


  protected class SWIGStringHelper {

    public delegate string SWIGStringDelegate(string message);
    static SWIGStringDelegate stringDelegate = new SWIGStringDelegate(CreateString);

    [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="SWIGRegisterStringCallback_cbj")]
    public static extern void SWIGRegisterStringCallback_cbj(SWIGStringDelegate stringDelegate);

    static string CreateString(string cString) {
      return cString;
    }

    static SWIGStringHelper() {
      SWIGRegisterStringCallback_cbj(stringDelegate);
    }
  }

  static protected SWIGStringHelper swigStringHelper = new SWIGStringHelper();


  public class SWIGStringWithLengthHelper {

    [global::System.Runtime.InteropServices.DllImport("cbj", EntryPoint="SWIG_csharp_string_to_c")]
    private static extern global::System.IntPtr SWIG_csharp_string_to_c0(int size, int len, [global::System.Runtime.InteropServices.In,global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.LPStr, SizeParamIndex=0)] string str);

    [global::System.Runtime.InteropServices.DllImport("cbj", EntryPoint="SWIG_csharp_string_size")]
    private static extern int SWIG_csharp_string_size(global::System.IntPtr str);

    [global::System.Runtime.InteropServices.DllImport("cbj", EntryPoint="SWIG_csharp_string_str")]
    private static extern global::System.IntPtr SWIG_csharp_string_str(global::System.IntPtr str);

    public static global::System.IntPtr SWIG_csharp_string_to_c(string str) {
      if (str == null)
        return global::System.IntPtr.Zero;
      global::System.Text.Encoding utf8 = global::System.Text.Encoding.UTF8;
      return SWIG_csharp_string_to_c0(utf8.GetByteCount(str), str.Length, str);
    }

    public static string SWIG_c_to_csharp_string(global::System.IntPtr str) {
      int size = SWIG_csharp_string_size(str);
      if (size > 0) {
        global::System.IntPtr s = SWIG_csharp_string_str(str);
        byte[] b = new byte[size];
        global::System.Runtime.InteropServices.Marshal.Copy(s, b, 0, size);
        global::System.Text.Encoding utf8 = global::System.Text.Encoding.UTF8;
        return utf8.GetString(b);
      }
      return null;
    }
  }


  static cbjPINVOKE() {
  }


  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_new_ChapterElement___")]
  public static extern global::System.IntPtr new_ChapterElement();

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_delete_ChapterElement___")]
  public static extern void delete_ChapterElement(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_ChapterElement_get_start_page_index___")]
  public static extern global::System.IntPtr ChapterElement_get_start_page_index(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_ChapterElement_get_mutable_start_page_index___")]
  public static extern global::System.IntPtr ChapterElement_get_mutable_start_page_index(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_ChapterElement_set_start_page_index___")]
  public static extern void ChapterElement_set_start_page_index(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_ChapterElement_get_summary___")]
  public static extern global::System.IntPtr ChapterElement_get_summary(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_ChapterElement_set_summary___")]
  public static extern void ChapterElement_set_summary(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_ChapterElement_get_title___")]
  public static extern string ChapterElement_get_title(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_ChapterElement_get_mutable_title___")]
  public static extern global::System.IntPtr ChapterElement_get_mutable_title(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_ChapterElement_set_title___")]
  public static extern void ChapterElement_set_title(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_new_CreatorElement___")]
  public static extern global::System.IntPtr new_CreatorElement();

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_delete_CreatorElement___")]
  public static extern void delete_CreatorElement(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_CreatorElement_get_name___")]
  public static extern string CreatorElement_get_name(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_CreatorElement_get_mutable_name___")]
  public static extern global::System.IntPtr CreatorElement_get_mutable_name(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_CreatorElement_set_name___")]
  public static extern void CreatorElement_set_name(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_CreatorElement_get_role___")]
  public static extern string CreatorElement_get_role(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_CreatorElement_get_mutable_role___")]
  public static extern global::System.IntPtr CreatorElement_get_mutable_role(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_CreatorElement_set_role___")]
  public static extern void CreatorElement_set_role(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_new_TagElement___")]
  public static extern global::System.IntPtr new_TagElement();

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_delete_TagElement___")]
  public static extern void delete_TagElement(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_TagElement_get_id___")]
  public static extern string TagElement_get_id(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_TagElement_get_mutable_id___")]
  public static extern global::System.IntPtr TagElement_get_mutable_id(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_TagElement_set_id___")]
  public static extern void TagElement_set_id(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_TagElement_get_name___")]
  public static extern string TagElement_get_name(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_TagElement_get_mutable_name___")]
  public static extern global::System.IntPtr TagElement_get_mutable_name(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_TagElement_set_name___")]
  public static extern void TagElement_set_name(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_TagElement_get_type___")]
  public static extern int TagElement_get_type(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_TagElement_get_mutable_type___")]
  public static extern global::System.IntPtr TagElement_get_mutable_type(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_TagElement_set_type___")]
  public static extern void TagElement_set_type(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_new_Metadata___")]
  public static extern global::System.IntPtr new_Metadata();

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_delete_Metadata___")]
  public static extern void delete_Metadata(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_Metadata_get_chapters___")]
  public static extern global::System.IntPtr Metadata_get_chapters(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_Metadata_get_mutable_chapters___")]
  public static extern global::System.IntPtr Metadata_get_mutable_chapters(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_Metadata_set_chapters___")]
  public static extern void Metadata_set_chapters(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_Metadata_get_creators___")]
  public static extern global::System.IntPtr Metadata_get_creators(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_Metadata_get_mutable_creators___")]
  public static extern global::System.IntPtr Metadata_get_mutable_creators(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_Metadata_set_creators___")]
  public static extern void Metadata_set_creators(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_Metadata_get_genres___")]
  public static extern global::System.IntPtr Metadata_get_genres(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_Metadata_get_mutable_genres___")]
  public static extern global::System.IntPtr Metadata_get_mutable_genres(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_Metadata_set_genres___")]
  public static extern void Metadata_set_genres(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_Metadata_get_issue___")]
  public static extern global::System.IntPtr Metadata_get_issue(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_Metadata_set_issue___")]
  public static extern void Metadata_set_issue(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_Metadata_get_language___")]
  public static extern global::System.IntPtr Metadata_get_language(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_Metadata_set_language___")]
  public static extern void Metadata_set_language(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_Metadata_get_publication_date___")]
  public static extern global::System.IntPtr Metadata_get_publication_date(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_Metadata_set_publication_date___")]
  public static extern void Metadata_set_publication_date(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_Metadata_get_publisher___")]
  public static extern global::System.IntPtr Metadata_get_publisher(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_Metadata_set_publisher___")]
  public static extern void Metadata_set_publisher(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_Metadata_get_series___")]
  public static extern string Metadata_get_series(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_Metadata_get_mutable_series___")]
  public static extern global::System.IntPtr Metadata_get_mutable_series(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_Metadata_set_series___")]
  public static extern void Metadata_set_series(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_Metadata_get_summary___")]
  public static extern global::System.IntPtr Metadata_get_summary(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_Metadata_set_summary___")]
  public static extern void Metadata_set_summary(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_Metadata_get_tags___")]
  public static extern global::System.IntPtr Metadata_get_tags(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_Metadata_get_mutable_tags___")]
  public static extern global::System.IntPtr Metadata_get_mutable_tags(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_Metadata_set_tags___")]
  public static extern void Metadata_set_tags(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_Metadata_get_title___")]
  public static extern string Metadata_get_title(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_Metadata_get_mutable_title___")]
  public static extern global::System.IntPtr Metadata_get_mutable_title(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_Metadata_set_title___")]
  public static extern void Metadata_set_title(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_Metadata_get_volume___")]
  public static extern global::System.IntPtr Metadata_get_volume(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_Metadata_set_volume___")]
  public static extern void Metadata_set_volume(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_new_PageTagElement___")]
  public static extern global::System.IntPtr new_PageTagElement();

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_delete_PageTagElement___")]
  public static extern void delete_PageTagElement(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_PageTagElement_get_tag_id___")]
  public static extern string PageTagElement_get_tag_id(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_PageTagElement_get_mutable_tag_id___")]
  public static extern global::System.IntPtr PageTagElement_get_mutable_tag_id(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_PageTagElement_set_tag_id___")]
  public static extern void PageTagElement_set_tag_id(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_PageTagElement_get_x___")]
  public static extern double PageTagElement_get_x(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_PageTagElement_get_mutable_x___")]
  public static extern global::System.IntPtr PageTagElement_get_mutable_x(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_PageTagElement_set_x___")]
  public static extern void PageTagElement_set_x(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_PageTagElement_get_y___")]
  public static extern double PageTagElement_get_y(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_PageTagElement_get_mutable_y___")]
  public static extern global::System.IntPtr PageTagElement_get_mutable_y(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_PageTagElement_set_y___")]
  public static extern void PageTagElement_set_y(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_new_PageElement___")]
  public static extern global::System.IntPtr new_PageElement();

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_delete_PageElement___")]
  public static extern void delete_PageElement(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_PageElement_get_base64_image___")]
  public static extern string PageElement_get_base64_image(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_PageElement_get_mutable_base64_image___")]
  public static extern global::System.IntPtr PageElement_get_mutable_base64_image(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_PageElement_set_base64_image___")]
  public static extern void PageElement_set_base64_image(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_PageElement_get_page_index___")]
  public static extern global::System.IntPtr PageElement_get_page_index(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_PageElement_get_mutable_page_index___")]
  public static extern global::System.IntPtr PageElement_get_mutable_page_index(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_PageElement_set_page_index___")]
  public static extern void PageElement_set_page_index(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_PageElement_get_page_tags___")]
  public static extern global::System.IntPtr PageElement_get_page_tags(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_PageElement_get_mutable_page_tags___")]
  public static extern global::System.IntPtr PageElement_get_mutable_page_tags(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_PageElement_set_page_tags___")]
  public static extern void PageElement_set_page_tags(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_PageElement_get_page_type___")]
  public static extern global::System.IntPtr PageElement_get_page_type(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_PageElement_get_mutable_page_type___")]
  public static extern global::System.IntPtr PageElement_get_mutable_page_type(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_PageElement_set_page_type___")]
  public static extern void PageElement_set_page_type(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_PageElement_get_summary___")]
  public static extern global::System.IntPtr PageElement_get_summary(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_PageElement_set_summary___")]
  public static extern void PageElement_set_summary(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_new_CbjzV1Schema___")]
  public static extern global::System.IntPtr new_CbjzV1Schema();

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_delete_CbjzV1Schema___")]
  public static extern void delete_CbjzV1Schema(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_CbjzV1Schema_get_metadata___")]
  public static extern global::System.IntPtr CbjzV1Schema_get_metadata(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_CbjzV1Schema_get_mutable_metadata___")]
  public static extern global::System.IntPtr CbjzV1Schema_get_mutable_metadata(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_CbjzV1Schema_set_metadata___")]
  public static extern void CbjzV1Schema_set_metadata(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_CbjzV1Schema_get_pages___")]
  public static extern global::System.IntPtr CbjzV1Schema_get_pages(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_CbjzV1Schema_get_mutable_pages___")]
  public static extern global::System.IntPtr CbjzV1Schema_get_mutable_pages(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_CbjzV1Schema_set_pages___")]
  public static extern void CbjzV1Schema_set_pages(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_CbjzV1Schema_get_version___")]
  public static extern string CbjzV1Schema_get_version(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_CbjzV1Schema_get_mutable_version___")]
  public static extern global::System.IntPtr CbjzV1Schema_get_mutable_version(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_CbjzV1Schema_set_version___")]
  public static extern void CbjzV1Schema_set_version(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_new_Cbj___")]
  public static extern global::System.IntPtr new_Cbj();

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_delete_Cbj___")]
  public static extern void delete_Cbj(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_Cbj_Open___")]
  public static extern bool Cbj_Open(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_Cbj_OpenCbjz___")]
  public static extern bool Cbj_OpenCbjz(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_Cbj_ImportFromCbz___")]
  public static extern bool Cbj_ImportFromCbz(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_Cbj_ImportFromCbr___")]
  public static extern bool Cbj_ImportFromCbr(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_Cbj_ImportFromCb7___")]
  public static extern bool Cbj_ImportFromCb7(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_Cbj_ImportFromCbt___")]
  public static extern bool Cbj_ImportFromCbt(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_Cbj_ImportFromPdf___")]
  public static extern bool Cbj_ImportFromPdf(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_Cbj_SaveAsCbjz___")]
  public static extern bool Cbj_SaveAsCbjz(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_Cbj_GetPages___")]
  public static extern global::System.IntPtr Cbj_GetPages(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_Cbj_GetPagesForView___")]
  public static extern global::System.IntPtr Cbj_GetPagesForView(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_Cbj_GetPage___")]
  public static extern global::System.IntPtr Cbj_GetPage(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_Cbj_ClearCache___")]
  public static extern void Cbj_ClearCache(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_Cbj_SetCachePages___")]
  public static extern void Cbj_SetCachePages(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_Cbj_GetCachePages___")]
  public static extern int Cbj_GetCachePages(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_Cbj_GetMetadata___")]
  public static extern global::System.IntPtr Cbj_GetMetadata(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_Cbj_SetMetadata___")]
  public static extern void Cbj_SetMetadata(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_Cbj_UpdatePage___")]
  public static extern void Cbj_UpdatePage(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_Cbj_GetTotalPages___")]
  public static extern int Cbj_GetTotalPages(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_Cbj_GetVersion___")]
  public static extern string Cbj_GetVersion(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_Cbj_IsOpen___")]
  public static extern bool Cbj_IsOpen(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_new_CbjBuilder___")]
  public static extern global::System.IntPtr new_CbjBuilder();

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_CbjBuilder_SetVersion___")]
  public static extern global::System.IntPtr CbjBuilder_SetVersion(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_CbjBuilder_SetMetadata___")]
  public static extern global::System.IntPtr CbjBuilder_SetMetadata(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, string jarg3);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_CbjBuilder_SetIssue___")]
  public static extern global::System.IntPtr CbjBuilder_SetIssue(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_CbjBuilder_SetVolume___")]
  public static extern global::System.IntPtr CbjBuilder_SetVolume(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_CbjBuilder_SetPublisher___")]
  public static extern global::System.IntPtr CbjBuilder_SetPublisher(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_CbjBuilder_SetLanguage___")]
  public static extern global::System.IntPtr CbjBuilder_SetLanguage(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_CbjBuilder_SetSummary___")]
  public static extern global::System.IntPtr CbjBuilder_SetSummary(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_CbjBuilder_AddGenre___")]
  public static extern global::System.IntPtr CbjBuilder_AddGenre(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_CbjBuilder_AddCreator___")]
  public static extern global::System.IntPtr CbjBuilder_AddCreator(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, string jarg3);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_CbjBuilder_AddTag___")]
  public static extern global::System.IntPtr CbjBuilder_AddTag(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, string jarg3, int jarg4);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_CbjBuilder_AddChapter__SWIG_0___")]
  public static extern global::System.IntPtr CbjBuilder_AddChapter__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, string jarg4);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_CbjBuilder_AddChapter__SWIG_1___")]
  public static extern global::System.IntPtr CbjBuilder_AddChapter__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_CbjBuilder_AddPageBase64__SWIG_0___")]
  public static extern global::System.IntPtr CbjBuilder_AddPageBase64__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, string jarg3, string jarg4);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_CbjBuilder_AddPageBase64__SWIG_1___")]
  public static extern global::System.IntPtr CbjBuilder_AddPageBase64__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, string jarg3);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_CbjBuilder_AddPageBase64__SWIG_2___")]
  public static extern global::System.IntPtr CbjBuilder_AddPageBase64__SWIG_2(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_CbjBuilder_AddPageBytes__SWIG_0___")]
  public static extern global::System.IntPtr CbjBuilder_AddPageBytes__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, string jarg3, string jarg4);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_CbjBuilder_AddPageBytes__SWIG_1___")]
  public static extern global::System.IntPtr CbjBuilder_AddPageBytes__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, string jarg3);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_CbjBuilder_AddPageBytes__SWIG_2___")]
  public static extern global::System.IntPtr CbjBuilder_AddPageBytes__SWIG_2(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_CbjBuilder_Build___")]
  public static extern global::System.IntPtr CbjBuilder_Build(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_CbjBuilder_Save___")]
  public static extern bool CbjBuilder_Save(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_delete_CbjBuilder___")]
  public static extern void delete_CbjBuilder(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_StringImageHelper_EncodeBase64__SWIG_0___")]
  public static extern string StringImageHelper_EncodeBase64__SWIG_0(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_StringImageHelper_EncodeBase64__SWIG_1___")]
  public static extern string StringImageHelper_EncodeBase64__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_StringImageHelper_DecodeBase64___")]
  public static extern string StringImageHelper_DecodeBase64(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_StringImageHelper_DecodeBase64Bytes___")]
  public static extern global::System.IntPtr StringImageHelper_DecodeBase64Bytes(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_StringImageHelper_ReadFile___")]
  public static extern string StringImageHelper_ReadFile(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_StringImageHelper_WriteFile___")]
  public static extern bool StringImageHelper_WriteFile(string jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_new_StringImageHelper___")]
  public static extern global::System.IntPtr new_StringImageHelper();

  [global::System.Runtime.InteropServices.DllImport("__Internal", EntryPoint="CSharp_ComicBookJsonfCbj_delete_StringImageHelper___")]
  public static extern void delete_StringImageHelper(global::System.Runtime.InteropServices.HandleRef jarg1);
}

}
