//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.5.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace ComicBookJson.Cbj {

public class CbjzV1Schema : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal CbjzV1Schema(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(CbjzV1Schema obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(CbjzV1Schema obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~CbjzV1Schema() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          cbjPINVOKE.delete_CbjzV1Schema(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public CbjzV1Schema() : this(cbjPINVOKE.new_CbjzV1Schema(), true) {
  }

  public Metadata get_metadata() {
    Metadata ret = new Metadata(cbjPINVOKE.CbjzV1Schema_get_metadata(swigCPtr), false);
    return ret;
  }

  public Metadata get_mutable_metadata() {
    Metadata ret = new Metadata(cbjPINVOKE.CbjzV1Schema_get_mutable_metadata(swigCPtr), false);
    return ret;
  }

  public void set_metadata(Metadata value) {
    cbjPINVOKE.CbjzV1Schema_set_metadata(swigCPtr, Metadata.getCPtr(value));
    if (cbjPINVOKE.SWIGPendingException.Pending) throw cbjPINVOKE.SWIGPendingException.Retrieve();
  }

  public SWIGTYPE_p_std__vectorT_cbjz__PageElement_t get_pages() {
    SWIGTYPE_p_std__vectorT_cbjz__PageElement_t ret = new SWIGTYPE_p_std__vectorT_cbjz__PageElement_t(cbjPINVOKE.CbjzV1Schema_get_pages(swigCPtr), false);
    return ret;
  }

  public SWIGTYPE_p_std__vectorT_cbjz__PageElement_t get_mutable_pages() {
    SWIGTYPE_p_std__vectorT_cbjz__PageElement_t ret = new SWIGTYPE_p_std__vectorT_cbjz__PageElement_t(cbjPINVOKE.CbjzV1Schema_get_mutable_pages(swigCPtr), false);
    return ret;
  }

  public void set_pages(SWIGTYPE_p_std__vectorT_cbjz__PageElement_t value) {
    cbjPINVOKE.CbjzV1Schema_set_pages(swigCPtr, SWIGTYPE_p_std__vectorT_cbjz__PageElement_t.getCPtr(value));
    if (cbjPINVOKE.SWIGPendingException.Pending) throw cbjPINVOKE.SWIGPendingException.Retrieve();
  }

  public string get_version() {
    string ret = cbjPINVOKE.CbjzV1Schema_get_version(swigCPtr);
    return ret;
  }

  public SWIGTYPE_p_std__string get_mutable_version() {
    SWIGTYPE_p_std__string ret = new SWIGTYPE_p_std__string(cbjPINVOKE.CbjzV1Schema_get_mutable_version(swigCPtr), false);
    return ret;
  }

  public void set_version(string value) {
    cbjPINVOKE.CbjzV1Schema_set_version(swigCPtr, value);
    if (cbjPINVOKE.SWIGPendingException.Pending) throw cbjPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
