//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.5.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace ComicBookJson.Cbj {

public class ChapterElement : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ChapterElement(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ChapterElement obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(ChapterElement obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~ChapterElement() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          cbjPINVOKE.delete_ChapterElement(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public ChapterElement() : this(cbjPINVOKE.new_ChapterElement(), true) {
  }

  public SWIGTYPE_p_int64_t get_start_page_index() {
    SWIGTYPE_p_int64_t ret = new SWIGTYPE_p_int64_t(cbjPINVOKE.ChapterElement_get_start_page_index(swigCPtr), false);
    return ret;
  }

  public SWIGTYPE_p_int64_t get_mutable_start_page_index() {
    SWIGTYPE_p_int64_t ret = new SWIGTYPE_p_int64_t(cbjPINVOKE.ChapterElement_get_mutable_start_page_index(swigCPtr), false);
    return ret;
  }

  public void set_start_page_index(SWIGTYPE_p_int64_t value) {
    cbjPINVOKE.ChapterElement_set_start_page_index(swigCPtr, SWIGTYPE_p_int64_t.getCPtr(value));
    if (cbjPINVOKE.SWIGPendingException.Pending) throw cbjPINVOKE.SWIGPendingException.Retrieve();
  }

  public SWIGTYPE_p_std__optionalT_std__string_t get_summary() {
    SWIGTYPE_p_std__optionalT_std__string_t ret = new SWIGTYPE_p_std__optionalT_std__string_t(cbjPINVOKE.ChapterElement_get_summary(swigCPtr), true);
    return ret;
  }

  public void set_summary(SWIGTYPE_p_std__optionalT_std__string_t value) {
    cbjPINVOKE.ChapterElement_set_summary(swigCPtr, SWIGTYPE_p_std__optionalT_std__string_t.getCPtr(value));
    if (cbjPINVOKE.SWIGPendingException.Pending) throw cbjPINVOKE.SWIGPendingException.Retrieve();
  }

  public string get_title() {
    string ret = cbjPINVOKE.ChapterElement_get_title(swigCPtr);
    return ret;
  }

  public SWIGTYPE_p_std__string get_mutable_title() {
    SWIGTYPE_p_std__string ret = new SWIGTYPE_p_std__string(cbjPINVOKE.ChapterElement_get_mutable_title(swigCPtr), false);
    return ret;
  }

  public void set_title(string value) {
    cbjPINVOKE.ChapterElement_set_title(swigCPtr, value);
    if (cbjPINVOKE.SWIGPendingException.Pending) throw cbjPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
