//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.5.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace ComicBookJson.Cbj {

public class Metadata : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Metadata(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Metadata obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(Metadata obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~Metadata() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          cbjPINVOKE.delete_Metadata(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public Metadata() : this(cbjPINVOKE.new_Metadata(), true) {
  }

  public SWIGTYPE_p_std__optionalT_std__vectorT_cbjz__ChapterElement_t_t get_chapters() {
    SWIGTYPE_p_std__optionalT_std__vectorT_cbjz__ChapterElement_t_t ret = new SWIGTYPE_p_std__optionalT_std__vectorT_cbjz__ChapterElement_t_t(cbjPINVOKE.Metadata_get_chapters(swigCPtr), false);
    return ret;
  }

  public SWIGTYPE_p_std__optionalT_std__vectorT_cbjz__ChapterElement_t_t get_mutable_chapters() {
    SWIGTYPE_p_std__optionalT_std__vectorT_cbjz__ChapterElement_t_t ret = new SWIGTYPE_p_std__optionalT_std__vectorT_cbjz__ChapterElement_t_t(cbjPINVOKE.Metadata_get_mutable_chapters(swigCPtr), false);
    return ret;
  }

  public void set_chapters(SWIGTYPE_p_std__optionalT_std__vectorT_cbjz__ChapterElement_t_t value) {
    cbjPINVOKE.Metadata_set_chapters(swigCPtr, SWIGTYPE_p_std__optionalT_std__vectorT_cbjz__ChapterElement_t_t.getCPtr(value));
    if (cbjPINVOKE.SWIGPendingException.Pending) throw cbjPINVOKE.SWIGPendingException.Retrieve();
  }

  public SWIGTYPE_p_std__optionalT_std__vectorT_cbjz__CreatorElement_t_t get_creators() {
    SWIGTYPE_p_std__optionalT_std__vectorT_cbjz__CreatorElement_t_t ret = new SWIGTYPE_p_std__optionalT_std__vectorT_cbjz__CreatorElement_t_t(cbjPINVOKE.Metadata_get_creators(swigCPtr), false);
    return ret;
  }

  public SWIGTYPE_p_std__optionalT_std__vectorT_cbjz__CreatorElement_t_t get_mutable_creators() {
    SWIGTYPE_p_std__optionalT_std__vectorT_cbjz__CreatorElement_t_t ret = new SWIGTYPE_p_std__optionalT_std__vectorT_cbjz__CreatorElement_t_t(cbjPINVOKE.Metadata_get_mutable_creators(swigCPtr), false);
    return ret;
  }

  public void set_creators(SWIGTYPE_p_std__optionalT_std__vectorT_cbjz__CreatorElement_t_t value) {
    cbjPINVOKE.Metadata_set_creators(swigCPtr, SWIGTYPE_p_std__optionalT_std__vectorT_cbjz__CreatorElement_t_t.getCPtr(value));
    if (cbjPINVOKE.SWIGPendingException.Pending) throw cbjPINVOKE.SWIGPendingException.Retrieve();
  }

  public SWIGTYPE_p_std__optionalT_std__vectorT_std__string_t_t get_genres() {
    SWIGTYPE_p_std__optionalT_std__vectorT_std__string_t_t ret = new SWIGTYPE_p_std__optionalT_std__vectorT_std__string_t_t(cbjPINVOKE.Metadata_get_genres(swigCPtr), false);
    return ret;
  }

  public SWIGTYPE_p_std__optionalT_std__vectorT_std__string_t_t get_mutable_genres() {
    SWIGTYPE_p_std__optionalT_std__vectorT_std__string_t_t ret = new SWIGTYPE_p_std__optionalT_std__vectorT_std__string_t_t(cbjPINVOKE.Metadata_get_mutable_genres(swigCPtr), false);
    return ret;
  }

  public void set_genres(SWIGTYPE_p_std__optionalT_std__vectorT_std__string_t_t value) {
    cbjPINVOKE.Metadata_set_genres(swigCPtr, SWIGTYPE_p_std__optionalT_std__vectorT_std__string_t_t.getCPtr(value));
    if (cbjPINVOKE.SWIGPendingException.Pending) throw cbjPINVOKE.SWIGPendingException.Retrieve();
  }

  public SWIGTYPE_p_std__optionalT_std__string_t get_issue() {
    SWIGTYPE_p_std__optionalT_std__string_t ret = new SWIGTYPE_p_std__optionalT_std__string_t(cbjPINVOKE.Metadata_get_issue(swigCPtr), true);
    return ret;
  }

  public void set_issue(SWIGTYPE_p_std__optionalT_std__string_t value) {
    cbjPINVOKE.Metadata_set_issue(swigCPtr, SWIGTYPE_p_std__optionalT_std__string_t.getCPtr(value));
    if (cbjPINVOKE.SWIGPendingException.Pending) throw cbjPINVOKE.SWIGPendingException.Retrieve();
  }

  public SWIGTYPE_p_std__optionalT_std__string_t get_language() {
    SWIGTYPE_p_std__optionalT_std__string_t ret = new SWIGTYPE_p_std__optionalT_std__string_t(cbjPINVOKE.Metadata_get_language(swigCPtr), true);
    return ret;
  }

  public void set_language(SWIGTYPE_p_std__optionalT_std__string_t value) {
    cbjPINVOKE.Metadata_set_language(swigCPtr, SWIGTYPE_p_std__optionalT_std__string_t.getCPtr(value));
    if (cbjPINVOKE.SWIGPendingException.Pending) throw cbjPINVOKE.SWIGPendingException.Retrieve();
  }

  public SWIGTYPE_p_std__optionalT_std__string_t get_publication_date() {
    SWIGTYPE_p_std__optionalT_std__string_t ret = new SWIGTYPE_p_std__optionalT_std__string_t(cbjPINVOKE.Metadata_get_publication_date(swigCPtr), true);
    return ret;
  }

  public void set_publication_date(SWIGTYPE_p_std__optionalT_std__string_t value) {
    cbjPINVOKE.Metadata_set_publication_date(swigCPtr, SWIGTYPE_p_std__optionalT_std__string_t.getCPtr(value));
    if (cbjPINVOKE.SWIGPendingException.Pending) throw cbjPINVOKE.SWIGPendingException.Retrieve();
  }

  public SWIGTYPE_p_std__optionalT_std__string_t get_publisher() {
    SWIGTYPE_p_std__optionalT_std__string_t ret = new SWIGTYPE_p_std__optionalT_std__string_t(cbjPINVOKE.Metadata_get_publisher(swigCPtr), true);
    return ret;
  }

  public void set_publisher(SWIGTYPE_p_std__optionalT_std__string_t value) {
    cbjPINVOKE.Metadata_set_publisher(swigCPtr, SWIGTYPE_p_std__optionalT_std__string_t.getCPtr(value));
    if (cbjPINVOKE.SWIGPendingException.Pending) throw cbjPINVOKE.SWIGPendingException.Retrieve();
  }

  public string get_series() {
    string ret = cbjPINVOKE.Metadata_get_series(swigCPtr);
    return ret;
  }

  public SWIGTYPE_p_std__string get_mutable_series() {
    SWIGTYPE_p_std__string ret = new SWIGTYPE_p_std__string(cbjPINVOKE.Metadata_get_mutable_series(swigCPtr), false);
    return ret;
  }

  public void set_series(string value) {
    cbjPINVOKE.Metadata_set_series(swigCPtr, value);
    if (cbjPINVOKE.SWIGPendingException.Pending) throw cbjPINVOKE.SWIGPendingException.Retrieve();
  }

  public SWIGTYPE_p_std__optionalT_std__string_t get_summary() {
    SWIGTYPE_p_std__optionalT_std__string_t ret = new SWIGTYPE_p_std__optionalT_std__string_t(cbjPINVOKE.Metadata_get_summary(swigCPtr), true);
    return ret;
  }

  public void set_summary(SWIGTYPE_p_std__optionalT_std__string_t value) {
    cbjPINVOKE.Metadata_set_summary(swigCPtr, SWIGTYPE_p_std__optionalT_std__string_t.getCPtr(value));
    if (cbjPINVOKE.SWIGPendingException.Pending) throw cbjPINVOKE.SWIGPendingException.Retrieve();
  }

  public SWIGTYPE_p_std__optionalT_std__vectorT_cbjz__TagElement_t_t get_tags() {
    SWIGTYPE_p_std__optionalT_std__vectorT_cbjz__TagElement_t_t ret = new SWIGTYPE_p_std__optionalT_std__vectorT_cbjz__TagElement_t_t(cbjPINVOKE.Metadata_get_tags(swigCPtr), false);
    return ret;
  }

  public SWIGTYPE_p_std__optionalT_std__vectorT_cbjz__TagElement_t_t get_mutable_tags() {
    SWIGTYPE_p_std__optionalT_std__vectorT_cbjz__TagElement_t_t ret = new SWIGTYPE_p_std__optionalT_std__vectorT_cbjz__TagElement_t_t(cbjPINVOKE.Metadata_get_mutable_tags(swigCPtr), false);
    return ret;
  }

  public void set_tags(SWIGTYPE_p_std__optionalT_std__vectorT_cbjz__TagElement_t_t value) {
    cbjPINVOKE.Metadata_set_tags(swigCPtr, SWIGTYPE_p_std__optionalT_std__vectorT_cbjz__TagElement_t_t.getCPtr(value));
    if (cbjPINVOKE.SWIGPendingException.Pending) throw cbjPINVOKE.SWIGPendingException.Retrieve();
  }

  public string get_title() {
    string ret = cbjPINVOKE.Metadata_get_title(swigCPtr);
    return ret;
  }

  public SWIGTYPE_p_std__string get_mutable_title() {
    SWIGTYPE_p_std__string ret = new SWIGTYPE_p_std__string(cbjPINVOKE.Metadata_get_mutable_title(swigCPtr), false);
    return ret;
  }

  public void set_title(string value) {
    cbjPINVOKE.Metadata_set_title(swigCPtr, value);
    if (cbjPINVOKE.SWIGPendingException.Pending) throw cbjPINVOKE.SWIGPendingException.Retrieve();
  }

  public SWIGTYPE_p_std__optionalT_int64_t_t get_volume() {
    SWIGTYPE_p_std__optionalT_int64_t_t ret = new SWIGTYPE_p_std__optionalT_int64_t_t(cbjPINVOKE.Metadata_get_volume(swigCPtr), true);
    return ret;
  }

  public void set_volume(SWIGTYPE_p_std__optionalT_int64_t_t value) {
    cbjPINVOKE.Metadata_set_volume(swigCPtr, SWIGTYPE_p_std__optionalT_int64_t_t.getCPtr(value));
    if (cbjPINVOKE.SWIGPendingException.Pending) throw cbjPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
