//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.5.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace ComicBookJson.Cbj {

public class TagElement : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal TagElement(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(TagElement obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(TagElement obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~TagElement() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          cbjPINVOKE.delete_TagElement(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public TagElement() : this(cbjPINVOKE.new_TagElement(), true) {
  }

  public string get_id() {
    string ret = cbjPINVOKE.TagElement_get_id(swigCPtr);
    return ret;
  }

  public SWIGTYPE_p_std__string get_mutable_id() {
    SWIGTYPE_p_std__string ret = new SWIGTYPE_p_std__string(cbjPINVOKE.TagElement_get_mutable_id(swigCPtr), false);
    return ret;
  }

  public void set_id(string value) {
    cbjPINVOKE.TagElement_set_id(swigCPtr, value);
    if (cbjPINVOKE.SWIGPendingException.Pending) throw cbjPINVOKE.SWIGPendingException.Retrieve();
  }

  public string get_name() {
    string ret = cbjPINVOKE.TagElement_get_name(swigCPtr);
    return ret;
  }

  public SWIGTYPE_p_std__string get_mutable_name() {
    SWIGTYPE_p_std__string ret = new SWIGTYPE_p_std__string(cbjPINVOKE.TagElement_get_mutable_name(swigCPtr), false);
    return ret;
  }

  public void set_name(string value) {
    cbjPINVOKE.TagElement_set_name(swigCPtr, value);
    if (cbjPINVOKE.SWIGPendingException.Pending) throw cbjPINVOKE.SWIGPendingException.Retrieve();
  }

  public Type get_type() {
    Type ret = (Type)cbjPINVOKE.TagElement_get_type(swigCPtr);
    return ret;
  }

  public SWIGTYPE_p_cbjz__Type get_mutable_type() {
    SWIGTYPE_p_cbjz__Type ret = new SWIGTYPE_p_cbjz__Type(cbjPINVOKE.TagElement_get_mutable_type(swigCPtr), false);
    return ret;
  }

  public void set_type(Type value) {
    cbjPINVOKE.TagElement_set_type(swigCPtr, (int)value);
  }

}

}
