//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace ComicBookJson.Cbj {

public class StringImageHelper : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal StringImageHelper(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(StringImageHelper obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(StringImageHelper obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~StringImageHelper() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          cbjPINVOKE.delete_StringImageHelper(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public static string EncodeBase64(string bytes) {
    string ret = cbjPINVOKE.StringImageHelper_EncodeBase64__SWIG_0(bytes);
    if (cbjPINVOKE.SWIGPendingException.Pending) throw cbjPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static string EncodeBase64(SWIGTYPE_p_std__vectorT_std__uint8_t_t bytes) {
    string ret = cbjPINVOKE.StringImageHelper_EncodeBase64__SWIG_1(SWIGTYPE_p_std__vectorT_std__uint8_t_t.getCPtr(bytes));
    if (cbjPINVOKE.SWIGPendingException.Pending) throw cbjPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static string DecodeBase64(string value) {
    string ret = cbjPINVOKE.StringImageHelper_DecodeBase64(value);
    if (cbjPINVOKE.SWIGPendingException.Pending) throw cbjPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static SWIGTYPE_p_std__vectorT_std__uint8_t_t DecodeBase64Bytes(string value) {
    SWIGTYPE_p_std__vectorT_std__uint8_t_t ret = new SWIGTYPE_p_std__vectorT_std__uint8_t_t(cbjPINVOKE.StringImageHelper_DecodeBase64Bytes(value), true);
    if (cbjPINVOKE.SWIGPendingException.Pending) throw cbjPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static string ReadFile(string path) {
    string ret = cbjPINVOKE.StringImageHelper_ReadFile(path);
    if (cbjPINVOKE.SWIGPendingException.Pending) throw cbjPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static bool WriteFile(string path, string bytes) {
    bool ret = cbjPINVOKE.StringImageHelper_WriteFile(path, bytes);
    if (cbjPINVOKE.SWIGPendingException.Pending) throw cbjPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public StringImageHelper() : this(cbjPINVOKE.new_StringImageHelper(), true) {
  }

}

}
